# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ask < Formula
  desc "Agent Skills Kit - The Package Manager for Agent Skills"
  homepage "https://github.com/yeasy/ask"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yeasy/ask/releases/download/v0.7.0/ask_0.7.0_darwin_amd64.tar.gz"
      sha256 "4dda4d451bd4e985eaee94386caa0a76d02a57d4a828125c2118eca745dd3c6a"

      def install
        bin.install "ask"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yeasy/ask/releases/download/v0.7.0/ask_0.7.0_darwin_arm64.tar.gz"
      sha256 "dd11a96973758f1943f4aa541f5c8d768fc1b9e91db259729bebbcb7ed65c0a5"

      def install
        bin.install "ask"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeasy/ask/releases/download/v0.7.0/ask_0.7.0_linux_amd64.tar.gz"
      sha256 "f5637d1ca21305e893694301c34b8778020d363c2d518d213d2908b124280417"
      def install
        bin.install "ask"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeasy/ask/releases/download/v0.7.0/ask_0.7.0_linux_arm64.tar.gz"
      sha256 "ef7bf8238413c4d7faff381623a9c5960883558989e8293ecaa76638f006bd9c"
      def install
        bin.install "ask"
      end
    end
  end

  test do
    system "#{bin}/ask", "--help"
  end
end
