# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ask < Formula
  desc "Agent Skills Kit - The Package Manager for Agent Skills"
  homepage "https://github.com/yeasy/ask"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yeasy/ask/releases/download/v0.6.1/ask_0.6.1_darwin_amd64.tar.gz"
      sha256 "3b40d7b22f7d05f39092d351f781d6efa4eddebf4952236fb4296cf23ca945ab"

      def install
        bin.install "ask"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yeasy/ask/releases/download/v0.6.1/ask_0.6.1_darwin_arm64.tar.gz"
      sha256 "a18c5091405e6d68c4b02d4654320f828608ed2611d8c52914436ea3f61bca48"

      def install
        bin.install "ask"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeasy/ask/releases/download/v0.6.1/ask_0.6.1_linux_amd64.tar.gz"
      sha256 "522d4c11471d7f9fb213e108b452318141d59d5398fe4e339e2bb984fb944ba6"
      def install
        bin.install "ask"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeasy/ask/releases/download/v0.6.1/ask_0.6.1_linux_arm64.tar.gz"
      sha256 "9bdc5515f4e125152f9d8c323727493695ea49b31a83f2c51a1817b6965acc6d"
      def install
        bin.install "ask"
      end
    end
  end

  test do
    system "#{bin}/ask", "--help"
  end
end
