# This file was generated by GoReleaser. DO NOT EDIT.
cask "ask" do
  version "1.11.0"

  on_macos do
    on_intel do
      sha256 "2370749895d07aaa1da48417302e8c1a2a559598d4ba5e2e1f84d201a875c353"
      url "https://github.com/yeasy/ask/releases/download/v#{version}/ask_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/yeasy/ask/"
    end
    on_arm do
      sha256 "f138d56aafaccea518021c0e5b5e2f7c8bd866070e9a8b09db12a7de51594de3"
      url "https://github.com/yeasy/ask/releases/download/v#{version}/ask_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/yeasy/ask/"
    end
  end

  on_linux do
    on_intel do
      sha256 "f3aa038968723f90b93724792a9312ed632405b65f31014ad86011754ab5aa1a"
      url "https://github.com/yeasy/ask/releases/download/v#{version}/ask_#{version}_linux_amd64.tar.gz",
        verified: "github.com/yeasy/ask/"
    end
    on_arm do
      sha256 "a6a2434546ddb4913772d75cf8a25eb1df534017f53a2270eb10fc0edb60a57b"
      url "https://github.com/yeasy/ask/releases/download/v#{version}/ask_#{version}_linux_arm64.tar.gz",
        verified: "github.com/yeasy/ask/"
    end
  end

  name "ask"
  desc "Agent Skills Kit - The Package Manager for Agent Skills"
  homepage "https://github.com/yeasy/ask"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ask"

  # No zap stanza required

end
