# This file was generated by GoReleaser. DO NOT EDIT.
cask "ask" do
  version "1.10.0"

  on_macos do
    on_intel do
      sha256 "2072af2599d0008f33477d5e73a04de086c939053ffe1a7b9e6b2aa10c8baa3f"
      url "https://github.com/yeasy/ask/releases/download/v#{version}/ask_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/yeasy/ask/"
    end
    on_arm do
      sha256 "fb2c5406635b1e4239fd1b7659263d8c0e6816e074cb7dd26983094f76be2566"
      url "https://github.com/yeasy/ask/releases/download/v#{version}/ask_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/yeasy/ask/"
    end
  end

  on_linux do
    on_intel do
      sha256 "cceb0f5a864846dae24318a3a959bd6cc13d80622eed11dfbd16d9ec4631702c"
      url "https://github.com/yeasy/ask/releases/download/v#{version}/ask_#{version}_linux_amd64.tar.gz",
        verified: "github.com/yeasy/ask/"
    end
    on_arm do
      sha256 "ed69eb3976c4991324d882e57b2a6589d2ce34ba8a6cdd4a4d15f497017e9d27"
      url "https://github.com/yeasy/ask/releases/download/v#{version}/ask_#{version}_linux_arm64.tar.gz",
        verified: "github.com/yeasy/ask/"
    end
  end

  name "ask"
  desc "Agent Skills Kit - The Package Manager for Agent Skills"
  homepage "https://github.com/yeasy/ask"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ask"

  # No zap stanza required

end
