# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdpress" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "eef5b59595277a7f8aa4e0f71929a9559de4281fba66e751620fc1a595281eb5"
      url "https://github.com/yeasy/mdpress/releases/download/v#{version}/mdpress_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/yeasy/mdpress/"
    end
    on_arm do
      sha256 "ab7553c8d189ded2fc11081a1e3584cbad13b85e215975e2607a6bb4d75dbb72"
      url "https://github.com/yeasy/mdpress/releases/download/v#{version}/mdpress_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/yeasy/mdpress/"
    end
  end

  on_linux do
    on_intel do
      sha256 "0f34ce38479d836e3f8914fe738fddae80aaaa8d205ccd202ba1945d1122c432"
      url "https://github.com/yeasy/mdpress/releases/download/v#{version}/mdpress_#{version}_linux_amd64.tar.gz",
        verified: "github.com/yeasy/mdpress/"
    end
    on_arm do
      sha256 "7a8f290bd3f73880f7f3b8fa55b7de718db598cf32641bedc235cb3935aace4a"
      url "https://github.com/yeasy/mdpress/releases/download/v#{version}/mdpress_#{version}_linux_arm64.tar.gz",
        verified: "github.com/yeasy/mdpress/"
    end
  end

  name "mdpress"
  desc "Markdown publishing CLI for book-style and documentation-style projects"
  homepage "https://github.com/yeasy/mdpress"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdpress"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdpress"]
    end
  end

  # No zap stanza required

end
