# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdpress" do
  version "0.7.12"

  on_macos do
    on_intel do
      sha256 "50909b8795ea4df7eb93412c1702c7b7286ca5bd915cc91531d576da0876e553"
      url "https://github.com/yeasy/mdpress/releases/download/v#{version}/mdpress_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/yeasy/mdpress/"
    end
    on_arm do
      sha256 "f9af3bda2b092d6a05b555162c851513a773912f6ed9b7ed2222858f2343e32c"
      url "https://github.com/yeasy/mdpress/releases/download/v#{version}/mdpress_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/yeasy/mdpress/"
    end
  end

  on_linux do
    on_intel do
      sha256 "7662d746057540ba2723dbfc454f99297fe480d7208647b9ce3083d111b7744f"
      url "https://github.com/yeasy/mdpress/releases/download/v#{version}/mdpress_#{version}_linux_amd64.tar.gz",
        verified: "github.com/yeasy/mdpress/"
    end
    on_arm do
      sha256 "b868758ced38887f1c27928400c7038d026eaa0d8bb40522a96b2c611871281c"
      url "https://github.com/yeasy/mdpress/releases/download/v#{version}/mdpress_#{version}_linux_arm64.tar.gz",
        verified: "github.com/yeasy/mdpress/"
    end
  end

  name "mdpress"
  desc "Markdown publishing CLI for book-style and documentation-style projects"
  homepage "https://github.com/yeasy/mdpress"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdpress"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdpress"]
    end
  end

  # No zap stanza required

end
