# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ask < Formula
  desc "Agent Skills Kit - The Package Manager for Agent Skills"
  homepage "https://github.com/yeasy/ask"
  version "1.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yeasy/ask/releases/download/v1.3.2/ask_1.3.2_darwin_amd64.tar.gz"
      sha256 "0a5df5c488c34d821d98924b04952b7b1809aa27eb36c43dce3ff5f1d899e485"

      def install
        bin.install "ask"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yeasy/ask/releases/download/v1.3.2/ask_1.3.2_darwin_arm64.tar.gz"
      sha256 "8a13d1d94f2b6120ec4687335680535deca3f202858293ac6cbae332ed646afb"

      def install
        bin.install "ask"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeasy/ask/releases/download/v1.3.2/ask_1.3.2_linux_amd64.tar.gz"
      sha256 "0c8552e569e2409d697f85f189d8d0fdce3c4e9ebba01e07e306df5ddbeb3199"
      def install
        bin.install "ask"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeasy/ask/releases/download/v1.3.2/ask_1.3.2_linux_arm64.tar.gz"
      sha256 "a83edf0223eaef13bdc968aa702a3ea32692c7b7f8380e2cc8a47c2bf1c937c9"
      def install
        bin.install "ask"
      end
    end
  end

  test do
    system "#{bin}/ask", "--help"
  end
end
