# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ask < Formula
  desc "Agent Skills Kit - The Package Manager for Agent Skills"
  homepage "https://github.com/yeasy/ask"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yeasy/ask/releases/download/v1.0.0/ask_1.0.0_darwin_amd64.tar.gz"
      sha256 "7f01ff56199e42ee7d9111dc676ca4732e5c5fd799ac5c1be76a03a1ecd8985f"

      def install
        bin.install "ask"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yeasy/ask/releases/download/v1.0.0/ask_1.0.0_darwin_arm64.tar.gz"
      sha256 "43b26581d3b7ccf49fed2fb498a32c90701cf4155f345ba190c27db7fa1cbf02"

      def install
        bin.install "ask"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeasy/ask/releases/download/v1.0.0/ask_1.0.0_linux_amd64.tar.gz"
      sha256 "2dcdb5545a99359cc3c7691f3cf554d0bb0e900db845dbe52421a8d6cbe2c958"
      def install
        bin.install "ask"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeasy/ask/releases/download/v1.0.0/ask_1.0.0_linux_arm64.tar.gz"
      sha256 "b9416a720260b9971735cb730e1a098cc1b8d16405adfc68bbf22cb26b6cf1c2"
      def install
        bin.install "ask"
      end
    end
  end

  test do
    system "#{bin}/ask", "--help"
  end
end
