# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdpress < Formula
  desc "Markdown publishing CLI for book-style and documentation-style projects"
  homepage "https://github.com/yeasy/mdpress"
  version "0.4.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yeasy/mdpress/releases/download/v0.4.3/mdpress_0.4.3_darwin_amd64.tar.gz"
      sha256 "8363568bed477b75d574bfb4b2ebc7e0ee32de54dbf4871f5e92781a9e6f836d"

      define_method(:install) do
        bin.install "mdpress"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yeasy/mdpress/releases/download/v0.4.3/mdpress_0.4.3_darwin_arm64.tar.gz"
      sha256 "c81b3adbdf2ee5b01d2e131f10eea98eb2fbbbb31d40ec643149a7f8461bc6aa"

      define_method(:install) do
        bin.install "mdpress"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeasy/mdpress/releases/download/v0.4.3/mdpress_0.4.3_linux_amd64.tar.gz"
      sha256 "db709180c626e2a31b8a6bc183f0fb113a6f9d070905801faa93f53912758788"
      define_method(:install) do
        bin.install "mdpress"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeasy/mdpress/releases/download/v0.4.3/mdpress_0.4.3_linux_arm64.tar.gz"
      sha256 "80a14fbc590d93998cb99931b7a0ce077576fbe808e5188f8a4d3dc890e4a5ef"
      define_method(:install) do
        bin.install "mdpress"
      end
    end
  end

  test do
    system "#{bin}/mdpress", "--help"
  end
end
